#! /bin/sh
### BEGIN INIT INFO
# Provides:          btsyncd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bittorent Sync
# Description:       Daemon for cluster bittorent sync system
### END INIT INFO

# Author: Albert Umerov <albert@veryware.org>
#

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME="btsync"
DESC="Bittorent Sync Daemon"

# Function that starts the daemon/service
#
do_start()
{
	sudo -u www-data -g cluster /usr/bin/btsync --config /etc/btsync.conf
}

#
# Function that stops the daemon/service
#
do_stop()
{
	killall btsync
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  status)
	echo "do nothing"
	;;
  restart|force-reload)
	do_stop
	sleep 5
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
